# Lab-Based Quiz 4  
# Time: 1 hour
## Comparing Individual Models vs Ensemble Methods  
### Dataset: Breast Cancer Wisconsin (Diagnostic)


## Objective

In this lab, you will:

1. Train and evaluate the following classifiers individually:
   - Decision Tree
   - Naive Bayes
   - K-Nearest Neighbors (KNN)
   - Logistic Regression
   - SGD Classifier

2. Build ensemble models using:
   - Hard Voting
   - Soft Voting
   - Bagging
   - Random Forest
   - AdaBoost

3. Compare all models using appropriate evaluation metrics.

4. Decide which metric best represents performance in this case study and justify your reasoning.

5. Write your own summary explaining your findings.

**Important**:
- Do NOT hard-code results.
- Do NOT use Gemini or any LLM model to do this for you.
- All answers must be written in your own words.
- Replace each TODO with working code.

# Part 1 – Load and Explore the Dataset

The Breast Cancer Wisconsin dataset is a binary classification dataset.

In [1]:
# TODO: Import necessary libraries
import pandas as pd
from sklearn.datasets import load_breast_cancer

# TODO: Load the breast cancer dataset from sklearn.datasets
data = load_breast_cancer()

# TODO: Convert the dataset to a pandas DataFrame (features + target)
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# TODO: Display the first 5 rows of the dataset
df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

## Basic Exploration

1. How many samples and features are there?
2. What are the target classes?
3. Is the dataset balanced?

In [2]:
# TODO: Print dataset shape
df.shape
# TODO: Print class distribution
df['target'].value_counts()
# TODO: Compute percentage of each class
df['target'].value_counts(normalize=True) * 100

target
1    62.741652
0    37.258348
Name: proportion, dtype: float64

### Write your answers below:

- Number of samples:
- Number of features:
- Class distribution:
- Is the dataset balanced?

# Part 2 – Train/Test Split and Scaling

In [3]:
# TODO: Perform train_test_split
# - 80% training
# - 20% testing
# - random_state=42
from sklearn.model_selection import train_test_split
X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# TODO: Apply StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# TODO: Fit scaler on training data only
scaler.fit(X_train)

# TODO: Transform both training and test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

### In 2–3 sentences:
Why is scaling necessary for some models but not for others?

scaling is necessary for some models and not other because some is becuase scalling is to remove the problem of feature dominace
some models dont need scalling like DT, randomforst etc because they dont need to worry about the difference in value sizes

# Part 3 – Train Individual Models

For EACH model:

* Train

* Predict

* Compute:

  * Accuracy

  * Precision

  * Recall

  * F1-score

  * Confusion Matrix

Store results for later comparison

In [5]:
# TODO: Import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

# TODO: Initialize model
dt = DecisionTreeClassifier(random_state=42)

# TODO: Fit model
dt.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred = dt.predict(X_test_scaled)

# TODO: Compute evaluation metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# TODO: Store results in a dictionary
results = {
    'accuracy' : accuracy, 
    'precision' : precision, 
    'recall' : recall,
    'f1' : f1
}

In [6]:
# TODO: Import GaussianNB
from sklearn.naive_bayes import GaussianNB

# TODO: Initialize model
clr_GaussianNB = GaussianNB() 

# TODO: Fit model
clr_GaussianNB.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_GaussianNB = clr_GaussianNB.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_GaussianNB = accuracy_score(y_test, y_pred_GaussianNB)
precision_GaussianNB = precision_score(y_test, y_pred_GaussianNB)
recall_GaussianNB = recall_score(y_test, y_pred_GaussianNB)
f1_GaussianNB = f1_score(y_test, y_pred_GaussianNB)

# TODO: Store results
# did it below

# TODO: Store results in a dictionary
results_GaussianNB = {
    'accuracy' : accuracy_GaussianNB, 
    'precision' : precision_GaussianNB, 
    'recall' : recall_GaussianNB,
    'f1' : f1_GaussianNB
}

In [7]:
# TODO: Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# TODO: Initialize model
clr_KNN = KNeighborsClassifier(n_neighbors=5) 

# TODO: Fit model
clr_KNN.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_KNN = clr_KNN.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_KNN = accuracy_score(y_test, y_pred_KNN)
precision_KNN = precision_score(y_test, y_pred_KNN)
recall_KNN = recall_score(y_test, y_pred_KNN)
f1_KNN = f1_score(y_test, y_pred_KNN)

# TODO: Store results
results_KNN = {
    'accuracy' : accuracy_KNN, 
    'precision' : precision_KNN, 
    'recall' : recall_KNN,
    'f1' : f1_KNN
}

c:\Users\longt\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\longt\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\longt\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\longt\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\longt\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [8]:
# TODO: Import LogisticRegression
from sklearn.linear_model import LogisticRegression

# TODO: Initialize model
clr_LR = LogisticRegression(random_state=42)

# TODO: Fit model
clr_LR.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_LR = clr_LR.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_LR = accuracy_score(y_test, y_pred_LR)
precision_LR = precision_score(y_test, y_pred_LR)
recall_LR = recall_score(y_test, y_pred_LR)
f1_LR = f1_score(y_test, y_pred_LR)

# TODO: Store results
results_LR = {
    'accuracy' : accuracy_LR, 
    'precision' : precision_LR, 
    'recall' : recall_LR,
    'f1' : f1_LR
}

In [9]:
# TODO: Import SGDClassifier
from sklearn.linear_model import SGDClassifier

# TODO: Initialize model
clr_SGD = SGDClassifier(random_state=42)

# TODO: Fit model
clr_SGD.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_SGD = clr_SGD.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_SGD = accuracy_score(y_test, y_pred_SGD)
precision_SGD = precision_score(y_test, y_pred_SGD)
recall_SGD = recall_score(y_test, y_pred_SGD)
f1_SGD = f1_score(y_test, y_pred_SGD)

# TODO: Store results
results_SGD = {
    'accuracy' : accuracy_SGD, 
    'precision' : precision_SGD, 
    'recall' : recall_SGD,
    'f1' : f1_SGD
}

# Part 4 – Voting Classifier

In [10]:
# TODO: Import VotingClassifier
from sklearn.ensemble import VotingClassifier
# TODO: Create hard voting classifier using at least 3 base models
voting_clf_hard = VotingClassifier(
    estimators=[('dt', dt), ('gnb', clr_GaussianNB), ('knn', clr_KNN)], 
    voting='hard'
)

# TODO: Fit model
voting_clf_hard.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_voting = voting_clf_hard.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_voting = accuracy_score(y_test, y_pred_voting)
precision_voting = precision_score(y_test, y_pred_voting)
recall_voting = recall_score(y_test, y_pred_voting)
f1_voting = f1_score(y_test, y_pred_voting)

# TODO: Store results
results_voting_hard = {
    'accuracy' : accuracy_voting, 
    'precision' : precision_voting, 
    'recall' : recall_voting,
    'f1' : f1_voting
}

In [11]:
# TODO: Create soft voting classifier
voting_clf_soft = VotingClassifier(
    estimators=[('dt', dt), ('gnb', clr_GaussianNB), ('knn', clr_KNN)], 
    voting='soft'
)

# NOTE: All models used must support predict_proba


# TODO: Fit model
voting_clf_soft.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_voting = voting_clf_soft.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_voting_soft  = accuracy_score(y_test, y_pred_voting)
precision_voting_soft  = precision_score(y_test, y_pred_voting)
recall_voting_soft  = recall_score(y_test, y_pred_voting)
f1_voting_soft = f1_score(y_test, y_pred_voting)

# TODO: Store results
results_voting_soft = {
    'accuracy' : accuracy_voting_soft, 
    'precision' : precision_voting_soft, 
    'recall' : recall_voting_soft,
    'f1' : f1_voting_soft
}

### In 2–3 sentences:
What is the difference between hard voting and soft voting?

with hard voting, it gets the the larget count of models prediction. basically the majority vote wins and that become the hard vote lable/class. While with soft voting, it get the average of the predicted class probablites, and choses baee off the highest average probabily

# Part 5 – Bagging and Boosting

In [12]:
# TODO: Import BaggingClassifier
from sklearn.ensemble import BaggingClassifier

# TODO: Initialize Bagging model (choose base estimator)
bagging_clf = BaggingClassifier(estimator=dt, n_estimators=100, random_state=42)

# TODO: Fit model
bagging_clf.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_bagging = bagging_clf.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_bagging = accuracy_score(y_test, y_pred_bagging)
precision_bagging = precision_score(y_test, y_pred_bagging)
recall_bagging = recall_score(y_test, y_pred_bagging)
f1_bagging = f1_score(y_test, y_pred_bagging)

# TODO: Store results
results_bagging = {
    'accuracy' : accuracy_bagging, 
    'precision' : precision_bagging, 
    'recall' : recall_bagging,
    'f1' : f1_bagging
}

In [13]:
# TODO: Import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# TODO: Initialize model

rf_clr = RandomForestClassifier(random_state=42)

# TODO: Fit model
rf_clr.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_rf = rf_clr.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

# TODO: Store results
results_rf = {
    'accuracy' : accuracy_rf, 
    'precision' : precision_rf, 
    'recall' : recall_rf,
    'f1' : f1_rf
}

In [14]:
# TODO: Import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

# TODO: Initialize model
ada_clf = AdaBoostClassifier(n_estimators=100, random_state=42)

# TODO: Fit model
ada_clf.fit(X_train_scaled, y_train)

# TODO: Predict
y_pred_ada = ada_clf.predict(X_test_scaled)

# TODO: Compute evaluation metrics
accuracy_ada = accuracy_score(y_test, y_pred_ada)
precision_ada = precision_score(y_test, y_pred_ada)
recall_ada = recall_score(y_test, y_pred_ada)
f1_ada = f1_score(y_test, y_pred_ada)

# TODO: Store results
results_ada = {
    'accuracy' : accuracy_ada, 
    'precision' : precision_ada, 
    'recall' : recall_ada,
    'f1' : f1_ada
}

c:\Users\longt\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

# Part 6 – Model Comparison

In [15]:
# TODO: Create a comparison DataFrame that includes:

# Model Name
# Accuracy
# Precision
# Recall
# F1-score

df_results = pd.DataFrame({
    'Model': ['Decision Tree', 'GaussianNB', 'KNN', 'Logistic Regression', 'SGD', 'Voting Classifier (Hard)', 'Voting Classifier (Soft)', 'Bagging Classifier', 'Random Forest', 'AdaBoost'],
    'Accuracy': [accuracy, accuracy_GaussianNB, accuracy_KNN, accuracy_LR, accuracy_SGD, accuracy_voting, accuracy_voting_soft, accuracy_bagging, accuracy_rf, accuracy_ada],
    'Precision': [precision, precision_GaussianNB, precision_KNN, precision_LR, precision_SGD, precision_voting, precision_voting_soft, precision_bagging, precision_rf, precision_ada],
    'Recall': [recall, recall_GaussianNB, recall_KNN, recall_LR, recall_SGD, recall_voting, recall_voting_soft, recall_bagging, recall_rf, recall_ada],
    'F1-score': [f1, f1_GaussianNB, f1_KNN, f1_LR, f1_SGD, f1_voting,f1_voting_soft , f1_bagging,f1_rf,f1_ada]
})

# TODO: Sort results by F1-score (descending)
df_results = df_results.sort_values(by='F1-score', ascending=False)

# TODO: Display the table
df_results

                      Model  Accuracy  Precision    Recall  F1-score
3       Logistic Regression  0.973684   0.972222  0.985915  0.979021
9                  AdaBoost  0.973684   0.972222  0.985915  0.979021
1                GaussianNB  0.964912   0.958904  0.985915  0.972222
5  Voting Classifier (Hard)  0.964912   0.958904  0.985915  0.972222
6  Voting Classifier (Soft)  0.964912   0.958904  0.985915  0.972222
8             Random Forest  0.964912   0.958904  0.985915  0.972222
4                       SGD  0.964912   0.985507  0.957746  0.971429
7        Bagging Classifier  0.956140   0.958333  0.971831  0.965035
0             Decision Tree  0.947368   0.957746  0.957746  0.957746
2                       KNN  0.947368   0.957746  0.957746  0.957746

In [16]:
# model that achieved the highest accuracy
highest_accuracy_model = df_results.loc[df_results['Accuracy'].idxmax()]
highest_accuracy_model

Model        Logistic Regression
Accuracy                0.973684
Precision               0.972222
Recall                  0.985915
F1-score                0.979021
Name: 3, dtype: object

In [17]:
highest_recall_model = df_results.loc[df_results['Recall'].idxmax()]
highest_recall_model

Model        Logistic Regression
Accuracy                0.973684
Precision               0.972222
Recall                  0.985915
F1-score                0.979021
Name: 3, dtype: object

In [18]:
# model that achieved the highest F1-score
highest_F1_score_model = df_results.loc[df_results['F1-score'].idxmax()]
highest_F1_score_model

Model        Logistic Regression
Accuracy                0.973684
Precision               0.972222
Recall                  0.985915
F1-score                0.979021
Name: 3, dtype: object

# Part 7 – Metric Selection and Interpretation

Answer the following:

1. Which model achieved the highest accuracy?
- Logistic Regression

2. Which model achieved the highest recall?
- Logistic Regression

3. Which model achieved the highest F1-score?
- Logistic Regression

4. In the context of breast cancer diagnosis:
   - Which metric is most important?
   - Why?
   the most important metric in the context of breast cancer would be the Recall because we want to find the ratio of correctly predicted postives. we dont want to miss identfiy a case, because if we miss a case, that would mean someone has cancer and they dont know

5. If a model has high accuracy but low recall, what does that imply in this medical context?
this would mean model may look good overall but is having high number of false negatives

# Part 8 – Final Reflection (Required)

## Final Reflection (1-2 paragraphs)

Write a short summary in your own words explaining:

- What you observed when comparing individual models vs ensemble models.
- Whether ensemble methods improved performance.
- Which model you would choose for real-world deployment.
- Which metric best represents performance in this case study and why.
- Any surprising findings.


### Your Reflection:

TODO: Write your summary here.
comparing the individual models vs ensemble models i found that the ensemble models acually worked better than 'most' models, them being 4th and 5th base on f1. i do think because of it higher ranking comared to other individual models, i think they improved performncae. other then models like log Reg, it was easter to interpret and already performed better than all other model includeing the ensemble models in baically all metrics. 

If i were to pick a model to use in real-world deplyment, i would pick using Log Reg, due to it out performing all other models steight out of the box. And if i were to uses one metric that would best represents the performce for this case study it would be with Recall due to the improtanct of brest canser. missing a true case (a false negative) is very bad, this would mean a system (some medical tech) failed to detect cancer in a pateint who should be getting treatment potentailly resulting in persons death when it could have been captured early and treated.